version: '2'
services:
    yupartymonolithic-app:
        image: yupartymonolithic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://yupartymonolithic-mysql:3306/yupartymonolithic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yupartymonolithic-mysql:
        extends:
            file: mysql.yml
            service: yupartymonolithic-mysql
